import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Sidebar from "@/components/features/sidebar"; // Import Sidebar
import Navbar from "@/components/features/navbar"; // Import Navbar

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen">
            {/* Sidebar fixed to the window height */}
            <div className="fixed top-0 bottom-0 w-[220px] md:w-[280px] z-10 bg-muted/40">
              <Sidebar /> {/* Sidebar added here */}
            </div>

            {/* Main content area with padding to avoid overlap with the sidebar */}
            <div className="flex-1 ml-[220px] md:ml-[280px]">
              <Navbar /> {/* Navbar added here */}
              <main className="overflow-auto p-5">{children}</main> {/* Scrollable content */}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
